# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-pub_date',)},
        ),
    ]
